spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/smart-home-tech
    driverClassName: org.postgresql.Driver
    username: sa
    password: sa
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create #none
    properties:
      hibernate:
        format_sql: true
        default_schema: warehouse
  application:
    name: warehouse

server:
  port: 4422