spring:
  datasource:
    url: jdbc:postgresql://localhost:9432/smart-home-warehouse
    driverClassName: org.postgresql.Driver
    username: sa
    password: sa
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create #none
    properties:
      hibernate:
        format_sql: true
  application:
    name: warehouse

server:
  port: 0