spring:
  datasource:
    url: jdbc:postgresql://localhost:12432/smart-home-delivery
    driverClassName: org.postgresql.Driver
    username: sa
    password: sa
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update #none
    properties:
      hibernate:
        format_sql: true
  application:
    name: delivery

server:
  port: 0